version: '3.7'

services:
  web:
    build: .
    restart: always
    command: bash -c "python StaskNew/manage.py migrate && python StaskNew/manage.py runserver 0.0.0.0:8000 & npm run dev"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: StaskNew
      